name: Default_World
main: com.ftwinston.KillerMinecraft.Modules.DefaultWorld.Plugin
depend: [Killer_Minecraft]
version: 1
load: STARTUP
description: A world generator for Killer Minecraft
author: FTWinston