name: Default World
main: com.ftwinston.KillerMinecraft.Modules.DefaultWorld.Plugin
depend: [Killer Minecraft]
version: 1
load: STARTUP
description: A world generator for Killer Minecraft
author: FTWinston